name: Build extension
run-name: Building Sidetabs 🚀
on: [push]

env:
  ARTIFACT_NAME: Sidetabs Bundle + Source code

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Zip Repository
        run: zip -r sidetabs-source.zip . -x .git/\*
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 
          cache: 'npm'
      - name: Install web-ext
        run: npm i -g web-ext
      - name: Install dependencies
        run: npm ci
      - name: Build sub-packages
        run: npm run build --workspaces
      - name: Build extension
        run: npm run build
      - name: Bundle extension
        run: npx web-ext build --artifacts-dir web-ext-artifacts
        working-directory: ./dist
      - name: Prepare upload
        run: |
          mkdir upload
          cp ./dist/web-ext-artifacts/*.zip upload
          cp sidetabs-source.zip upload
      - name: Upload extension bundle + source code
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: upload/*
          if-no-files-found: error